# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    veruscript.submission.factory:
        class: AppBundle\Factory\SubmissionFactory

    veruscript.author.factory:
        class: AppBundle\Factory\AuthorFactory
